#
# You, i.e. the account-in-which-is-being-used-to-develop-this-extension's Steam64 UID
# Required
my_steam_uid: YOUR_UID

#
# A list of valid Steam UIDs that matches the list used by the esm_bot's testing suite
# Required
steam_uids:
- UID_1
- UID_2

#
# Config for the Linux Arma 3 server
server:
  # Steam username used to login to steamcmd
  # This account does not need to own Arma 3, but must have Steam Guard disabled
  steam_user: account_steam_name

  # The password for the above account used to login to steamcmd
  # Password cannot contain any un-escaped special characters, nor can it be more than 64 characters long
  steam_password: account_password

  # The connection URI (e.g. mysql://user:password@ip_or_domain:port/database) for the same MySQL server as defined in the config file for extDB2/3
  # This is already pre-configured to work with the docker image
  mysql_uri: mysql://root:password12345@mysql_db:3306/exile_esm

  # The command line arguments that are given to the Arma 3 server
  # Omit the dash (-) prefix. It is added automatically.
  # Linux must escape the semi-colons
  server_args:
  - mod=@exile\;
  - servermod=@exileserver\;@esm\;
  - config=@exileserver/config.cfg
  - port=2302
  - profiles=server_profile
  - cfg=@exileserver/basic.cfg
  - name=server_profile
  - autoinit
  - enableHT
  - loadMissionToMemory
  - world=empty
  - noSound
  - nosplash
