#
# You, i.e. the account-in-which-is-being-used-to-develop-this-extension's Steam64 UID
# Required
my_steam_uid: YOUR_UID

#
# A list of valid Steam UIDs that matches the list used by the esm_bot's testing suite
# Required
steam_uids:
  - UID_1
  - UID_2

#
# Config for the Linux Arma 3 server
server:
  # Steam username used to login to steamcmd
  # This account does not need to own Arma 3, but must have Steam Guard disabled
  steam_user: account_steam_name

  # The password for the above account used to login to steamcmd
  # Password cannot contain any un-escaped special characters, nor can it be more than 64 characters long
  steam_password: account_password