version: '3.8'
services:
  arma_server:
    build: .
    platform: linux/amd64
    container_name: ESM_ARMA_SERVER
    network_mode: host
    volumes:
      - './server/@exileserver:/arma3server/@exileserver'
      - './server/mpmissions:/arma3server/mpmissions'
      - 'server-data:/arma3server'
      - 'steam-data:/steamcmd'
    tty: true
    # restart: unless-stopped
  mysql_db:
    image: mysql:8
    container_name: ESM_DB_MYSQL
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./exile.sql:/docker-entrypoint-initdb.d/exile.sql
    restart: unless-stopped
volumes:
  mysql-data:
  server-data:
  steam-data:
