version: '3.8'
services:
  arma_server:
    build: .
    container_name: ESM_ARMA_SERVER
    volumes:
      - './server/@exile:/arma3server/@exile'
      - './server/@exileserver:/arma3server/@exileserver'
      - './server/mpmissions:/arma3server/mpmissions'
      - 'server-data:/arma3server'
      - 'steam-data:/steamcmd'
      - 'tmp-data:/tmp'
    tty: true
    networks:
      - dev
    extra_hosts: # Allows linux host to use host.docker.internal.
      - "host.docker.internal:host-gateway"
  mysql_db:
    image: mysql:8
    container_name: ESM_DB_MYSQL
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./exile.sql:/docker-entrypoint-initdb.d/exile.sql
    networks:
      - dev
  mysql_db_v1:
    image: mysql:5.7
    container_name: ESM_DB_MYSQL_V1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./exile.sql:/docker-entrypoint-initdb.d/exile.sql
    networks:
      - dev
    profiles:
      - v1

volumes:
  mysql-data:
  server-data:
  steam-data:
  tmp-data:

networks:
  dev:
    driver: bridge
