[package]
name = "esm"
version = "2.0.0"
authors = ["Bryan <WolfkillArcadia@gmail.com>"]
edition = "2018"

[lib]
name = "esm_arma"
crate-type = ["cdylib", "rlib"]

# [[bin]]
# name = "esm_bin"
# path = "src/bin/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arma-rs = { version = "1.9", features = ["uuid", "serde_json", "chrono"] }
base64 = "0.21"
chrono = { version = "0.4", features = ["serde"] }
esm_message = { path = "../message/message" }
harsh = "0.2.2"
lazy_static = "1.4.0"
log = "*"
log4rs = "*"
message-io = { version = "0.17", default-features = false, features = ["tcp"] }
mysql_async = "0.32"
parking_lot = { version = "0.12.1", features = ["serde", "deadlock_detection"] }
rand = "*"
rust-ini = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
serde_repr = "0.1"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.3", features = ["serde", "v4", "fast-rng"] }
aes-gcm = "0.9.1"

[dev-dependencies]
pretty_assertions = "1.3"
regex = "1"

[dependencies.mysql_common]
version = "0.30.4"
features = ["chrono"]
