[package]
name = "esm"
version = "2.0.0"
authors = ["Bryan <WolfkillArcadia@gmail.com>"]
edition = "2018"

[lib]
name = "esm_arma"
crate-type = ["cdylib", "rlib"]

# [[bin]]
# name = "esm_bin"
# path = "src/bin/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
arma-rs = { version = "1.9", features = ["uuid", "serde_json", "chrono"] }
base64 = "0.12.3"
log = "0.4.11"
lazy_static = "1.4.0"
log4rs = "0.13.0"
chrono = { version = "0.4", features = ["serde"] }
rust-ini = "0.16.1"
esm_message = { path = "../message/message" }
message-io = { version = "0.14", default-features = false, features = ["tcp"] }
serde_yaml = "0.8"
uuid = { version = "1.1", features = ["serde", "v4", "fast-rng"] }
mysql_async = "0.30.0"
tokio = { version = "1.20.1", features = ["full"] }
rand = "0.8"

[dev-dependencies]
pretty_assertions = "0.6.1"
regex = "1"
