# @esm's configuration file
# You can override any of the following options:
#   connection_url:             The URL that esm_server is running on plus the port: "esmbot.com:80"
#   log_level:                  The verbosity level of the internal logger. Valid options: trace, debug, info, warn, error
#   extdb_conf_path:            The full path plus filename for the extDB config
#   extdb_conf_header_name:     The name of the section header in ExtDB's config file. This section contains the connection details for the database
#   extdb_version:              The version of ExtDB the server is using. This is mainly used for development
#   logging_path:               The full path plus filename for the extension to log to
#   env:                        The ENV that the code should run in. Valid options: production, test, development
